CREATE DATABASE IF NOT EXISTS ALGO_DATA;

CREATE TABLE ALGO_VALUES(
	T_MS BIGINT NOT NULL, 
    EXCHANGE_SYMBOL_ID INT NOT NULL,
    ZSCORE DECIMAL(20,8) NOT NULL, 
    HURST DECIMAL(20,8) NOT NULL,
    THETA DECIMAL(20,8) NOT NULL,
    HALFLIFE DECIMAL(20,8) NOT NULL,
    MU DECIMAL(20,8) NOT NULL,
    PRIMARY KEY (T_MS, EXCHANGE_SYMBOL_ID)
);

