CREATE DATABASE IF NOT EXISTS MARKET_DATA;
CREATE TABLE EXCHANGE_DATA(
	EXCHANGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    EXCHANGE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE SYMBOL_DATA(
	SYMBOL_ID INT AUTO_INCREMENT PRIMARY KEY,
    SYMBOL_CODE VARCHAR(25) NOT NULL
);

CREATE TABLE EXCHANGE_SYMBOL(
	EXCHANGE_SYMBOL_ID INT AUTO_INCREMENT PRIMARY KEY, 
    EXCHANGE_ID INT NOT NULL, 
    SYMBOL_ID INT NOT NULL, 
    DETAILS VARCHAR(250),
    FOREIGN KEY (EXCHANGE_ID) REFERENCES EXCHANGE_DATA(EXCHANGE_ID),
    FOREIGN KEY (SYMBOL_ID) REFERENCES SYMBOL_DATA(SYMBOL_ID),
    INDEX idx_exchange_symbol (EXCHANGE_ID, SYMBOL_ID)
);

CREATE TABLE MID_CANDLES_5M(
	T_MS BIGINT NOT NULL,
    EXCHANGE_SYMBOL_ID INT,
    SYMBOL VARCHAR(50),
    MID_OPEN DECIMAL(20,8) NOT NULL,
    MID_CLOSE DECIMAL(20,8) NOT NULL,
    MID_HIGH DECIMAL(20,8) NOT NULL,
    MID_LOW DECIMAL(20,8) NOT NULL,
    VOLUME DECIMAL(20,8) NOT NULL,
    PRIMARY KEY (T_MS, EXCHANGE_SYMBOL_ID),
    FOREIGN KEY (EXCHANGE_SYMBOL_ID) REFERENCES EXCHANGE_SYMBOL(EXCHANGE_SYMBOL_ID),
	INDEX idx_symbol_time (EXCHANGE_SYMBOL_ID, T_MS) 
);


